### PR TITLE
Create basic configuration and info files

### PR DESCRIPTION
**Pull request by serhii73**
Adding the necessary settings for the project

### CODE REVIEW

**Comment by webknjaz** [comment]
PR description just repeats title, not explaining anything

**Comment by webknjaz** [comment]
Readme should be in this PR, not in master

**Comment by webknjaz** [comment]
> Adding the necessary settings for the project

this is a pointless description

**Comment by serhii73** [comment]
@webknjaz I worked with `git` and I don't understand why the PR closed.
Interestingly, I went not to the site and did not close it.
And I can't open it again, the button does not work.

**Comment by serhii73** [comment]
> this is a pointless description
If I delete it, it's way out in this situation?

**Comment by serhii73** [comment]
@webknjaz may be to delete the branch and to create new?
`Delete branch` - active button for me.

**Comment by webknjaz** [comment]
you should fix things, not delete

**Pull request closed without merging**
