### PR TITLE
Add post model to admin

### PR DESCRIPTION
**Pull request by serhii73**
Show post model in the admin interface.

### CODE REVIEW

**Comment by webknjaz** [comment]
why did you close it?

**Comment by serhii73** [comment]
@webknjaz Something I have done with this branch.
`git rebase master` did then solve the conflicts, `git add`s file and then `git rebase --continue`, tried to push - nothing.
`git rebase --skip` and pushed with the flag `--force` and everything, the branch was deleted.
Something wrong I did ... apparently, the skip was superfluous. And now what I can do?

**Comment by webknjaz** [comment]
1. To avoid such things I usually create a backup branch.
2. You shouldn't close PRs, continue where you started.
3. It's a chance to learn how to recover things in git, like using reflog. You must have smth locally. Then you can practice rebasing again.
4. You should've checked the branch locally. Force push is dangerous in many ways.

**Comment by webknjaz** [comment]
> do you do that?

No, I just create a branch with backup suffix and operate on original branch and then I can compare them via git diff, for example

> What am I supposed to do with this branch? Now?

Google how to recover lost branch using git reflog.

> Tell me, what do you mean?

You still had an original branch on remote right up to the point when you force pushed your broken local branch there.

**Comment by serhii73** [comment]
`--skip` was my big mistake. I read about it. Now hardly a repeat.

**Comment by webknjaz** [comment]
Yep :)
Did you finally get the idea of what's happening during rebase?

**Comment by serhii73** [comment]
I explain how I understand it, @webknjaz 
`Branch` is the first chain and `master` is the second chain.
And they join to each other. Is a straight line.
But if it `merge` we can see a circle.
In the end, no difference. We have a master code in first and second case.

> Once you understand what rebasing is, the most important thing to learn is when not to do it. The golden rule of git rebase is to never use it on public branches.

from [tutorials - merging-vs-rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)

I think I'm still not understand for 100%. =(

**Comment by webknjaz** [comment]
> public branches

It means the branches, where you collaborate with other people. It's usually about `master` or `devel`, or `release`. Not feature-branches for PRs.

**Comment by webknjaz** [comment]
Rebase takes a set of commits you give it and then applies them sequentially one by one to the target branch in the same order.

**Comment by webknjaz** [comment]
"branch" in git is a pointer to some commit, which corresponds to that commit and chain of all of the parent commits of that commits.

When you create a "merge commit", it's just like normal commit, except it contains pointer to more than one commit. (two or more parrent chains joining together).

_**Fun fact:** merges with more than one parent are called "octopus" :)_

**Pull request closed without merging**
